modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/EdwinMindcraft/origins-architectury/issues"

[[mods]]
modId="origins"
version="${version}"
displayName="Origins"
#logoFile=
authors="Apace"
description='''
This mod adds several origins with passive abilities to the game, which you can choose from at the beginning of the game.
'''

[[dependencies.origins]]
    modId="forge"
    mandatory=true
    versionRange="${forge_requirements}"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins]]
    modId="calio"
    mandatory=true
    versionRange="[1.18.1-1.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.origins]]
    modId="apoli"
    mandatory=true
    versionRange="[1.18.1-2.2,)"
    ordering="NONE"
    side="BOTH"